name: SuddenDeath
version: ${project.version}
main: net.Indyuce.suddendeath.SuddenDeath
author: Indyuce
description: ${project.description}
softdepend: [WorldGuard]
api-version: 1.18
commands:
    sdstatus:
        description: Shows your current status (bleeding, ...).
        aliases: [sds,suddendeath]
    sdmob:
        description: Main command from the custom monster system.
        aliases: [sdmonster]
permissions:
    suddendeath.status:
        default: op
    suddendeath.op:
        default: op
    suddendeath.update-notify:
        default: op
    suddendeath.difficulty.*:
        default: op
        children:
            suddendeath.difficulty.sandbox: true
            suddendeath.difficulty.difficult: true
            suddendeath.difficulty.hardcore: true
            suddendeath.difficulty.death-wish: true
            suddendeath.difficulty.sudden-death: true